
package View;

import Model.Product;

public class jifHome extends javax.swing.JFrame {

    public static boolean Registration;

    public jifHome() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jdpHome = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmNewTransaction = new javax.swing.JMenuItem();
        jmListTransactions = new javax.swing.JMenuItem();
        jmProduct = new javax.swing.JMenu();
        jmNewProduct = new javax.swing.JMenuItem();
        jmStoreProducts = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales and Control");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dollars-on-wooden-cubes-arrangement (3).jpg"))); // NOI18N
        jLabel1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/dollars-on-wooden-cubes-arrangement (2).jpg"))); // NOI18N
        jLabel1.setMaximumSize(null);
        jLabel1.setMinimumSize(null);
        jLabel1.setPreferredSize(null);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jdpHome.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpHomeLayout = new javax.swing.GroupLayout(jdpHome);
        jdpHome.setLayout(jdpHomeLayout);
        jdpHomeLayout.setHorizontalGroup(
            jdpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpHomeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdpHomeLayout.setVerticalGroup(
            jdpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpHomeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 549, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        jMenu1.setForeground(new java.awt.Color(45, 52, 54));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaction (1).png"))); // NOI18N
        jMenu1.setText("Transações");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jmNewTransaction.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jmNewTransaction.setText("Nova");
        jmNewTransaction.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jmNewTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNewTransactionActionPerformed(evt);
            }
        });
        jMenu1.add(jmNewTransaction);

        jmListTransactions.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jmListTransactions.setText("Listar Transações");
        jmListTransactions.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jmListTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListTransactionsActionPerformed(evt);
            }
        });
        jMenu1.add(jmListTransactions);

        jMenuBar1.add(jMenu1);

        jmProduct.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        jmProduct.setForeground(new java.awt.Color(45, 52, 54));
        jmProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sapatos-femininos.png"))); // NOI18N
        jmProduct.setText("Produtos");
        jmProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jmNewProduct.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jmNewProduct.setText("Criar Produto");
        jmNewProduct.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jmNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNewProductActionPerformed(evt);
            }
        });
        jmProduct.add(jmNewProduct);

        jmStoreProducts.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jmStoreProducts.setText("Estoque");
        jmStoreProducts.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jmStoreProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmStoreProductsActionPerformed(evt);
            }
        });
        jmProduct.add(jmStoreProducts);

        jMenuBar1.add(jmProduct);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmListTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListTransactionsActionPerformed
        // TODO add your handling code here:
        jifTransactions transactionsScream =new jifTransactions();
        
        jdpHome.add(transactionsScream);
        transactionsScream.setVisible(true);
    }//GEN-LAST:event_jmListTransactionsActionPerformed

    private void jmNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNewProductActionPerformed

        if (Registration == false) {
            jifNewProduct newProduct = new jifNewProduct();
            jdpHome.add(newProduct);

            newProduct.setVisible(true);
        } //fim do if
    }//GEN-LAST:event_jmNewProductActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Código para a tela ficar do tamanho da tela do monitor
        this.setExtendedState(MAXIMIZED_BOTH);

        // Código para Não duplicar a tela de Cadastro de produtos
        jifHome.Registration = false;
    }//GEN-LAST:event_formWindowOpened

    private void jmStoreProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmStoreProductsActionPerformed
        jifProducts storeProducts = new jifProducts();
        jdpHome.add(storeProducts);

        storeProducts.setVisible(true);
    }//GEN-LAST:event_jmStoreProductsActionPerformed

    private void jmNewTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNewTransactionActionPerformed
        jifNewTransaction newTransactionscream = new jifNewTransaction(this, true);
        
        newTransactionscream.setVisible(true);
        
        
    }//GEN-LAST:event_jmNewTransactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jifHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jifHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jifHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jifHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jifHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdpHome;
    private javax.swing.JMenuItem jmListTransactions;
    private javax.swing.JMenuItem jmNewProduct;
    private javax.swing.JMenuItem jmNewTransaction;
    private javax.swing.JMenu jmProduct;
    private javax.swing.JMenuItem jmStoreProducts;
    // End of variables declaration//GEN-END:variables
}
