
package View;

import Controller.ProductsDAO;
import Model.Product;
import java.util.Date;
import javax.swing.JOptionPane;

public class jifNewProduct extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifNewProduct
     */
    public jifNewProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlName = new javax.swing.JLabel();
        jtNameProduct = new javax.swing.JTextField();
        jlSize = new javax.swing.JLabel();
        jtSize = new javax.swing.JTextField();
        jtColor = new javax.swing.JTextField();
        jlColor = new javax.swing.JLabel();
        jbSave = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro de Produto");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jlName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jlName.setText("Nome do Produto");

        jtNameProduct.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jlSize.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jlSize.setText("Tamanho");

        jtSize.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSizeActionPerformed(evt);
            }
        });

        jtColor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jlColor.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jlColor.setText("Cor");

        jbSave.setBackground(new java.awt.Color(108, 92, 231));
        jbSave.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbSave.setForeground(new java.awt.Color(223, 230, 233));
        jbSave.setText("Salvar");
        jbSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtNameProduct)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jtSize, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtColor)
                            .addComponent(jlColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlName)
                        .addGap(0, 259, Short.MAX_VALUE))
                    .addComponent(jbSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNameProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtColor, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jtSize))
                .addGap(18, 18, 18)
                .addComponent(jbSave, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        setBounds(210, 20, 400, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSizeActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        
        Product product = new Product();
        ProductsDAO productsController = new ProductsDAO();
        
        
        product.setName(jtNameProduct.getText());
        product.setSize(Integer.parseInt(jtSize.getText()));
        product.setColor(jtColor.getText());
        product.setCreated_at(new Date());
        
        productsController.save(product);
        
        JOptionPane.showMessageDialog(null,"Produto Criado com sucesso");
        
        dispose();
        
        
    }//GEN-LAST:event_jbSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSave;
    private javax.swing.JLabel jlColor;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlSize;
    private javax.swing.JTextField jtColor;
    private javax.swing.JTextField jtNameProduct;
    private javax.swing.JTextField jtSize;
    // End of variables declaration//GEN-END:variables
}
